"""first migrate

Revision ID: 3809780b1b31
Revises: 
Create Date: 2020-02-19 19:38:07.578285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3809780b1b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity_btc', sa.Float(), nullable=True),
    sa.Column('quantity_xrp', sa.Float(), nullable=True),
    sa.Column('quantity_xlm', sa.Float(), nullable=True),
    sa.Column('quantity_gld', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    # ### end Alembic commands ###
