"""second migrate

Revision ID: c7bf4d772a42
Revises: 3809780b1b31
Create Date: 2020-02-24 21:30:33.833513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bf4d772a42'
down_revision = '3809780b1b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity_btc', sa.Float(), nullable=True),
    sa.Column('quantity_xrp', sa.Float(), nullable=True),
    sa.Column('quantity_xlm', sa.Float(), nullable=True),
    sa.Column('quantity_gld', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('assets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_btc', sa.FLOAT(), nullable=True),
    sa.Column('quantity_xrp', sa.FLOAT(), nullable=True),
    sa.Column('quantity_xlm', sa.FLOAT(), nullable=True),
    sa.Column('quantity_gld', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('asset')
    # ### end Alembic commands ###
